version: '2'

services:
    web:
      container_name: my_app
      build: .
      links:
        - redis
        - mariadb

    nginx:
      container_name: nginx
      image: nginx
      links:
        - my_app
      ports:
        - 80:80
        - 443:443

    redis:
      container_name: redis
      image: redis

    mariadb:
      container_name: mariadb
      image: mariadb
